### ISSUE TITLE
Opensource license?

### ISSUE THREAD

**Issue by ochafik** [sofian/openscad-tray#1]
Hi, cool lib!
I'm looking at which libraries to make available in https://ochafik.com/openscad (probably soon to become the official playground) and thought about your library, but it has no license. Would you consider opensourcing it?

Thanks!

**Comment by sofian** [comment]
Oh it's just that I forgot. Here, just added a LICENSE file (GPL v3).

**Comment by ochafik** [comment]
Thanks! It doesn't seem to render yet, but at least it's got some amount of autocompletion :-)

<img width="532" alt="image" src="https://user-images.githubusercontent.com/273860/159164087-d76ef5d3-1902-4cc3-99e3-6a6dc10a7527.png">
